name: mekal
description: Mekal projets.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  shared_preferences: ^2.1.0
  google_fonts: ^4.0.4
  cloud_firestore: ^4.6.0
  provider: ^6.0.5
  flutter_barcode_scanner: ^2.0.0
  intl: ^0.17.0
  uuid: ^3.0.7
  image_picker: ^0.8.7+5
  flutter_slimy_card: ^1.0.2
  speed_dial_fab: ^2.3.0
  share_plus: ^7.0.1
  brasil_fields: ^1.9.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/pic/
  